StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{61CF39320BCCAA57}" {
   Id "#DRG_PC_Gen_III_Base_AR_Desc"
   Target_en_us "Developed by Podval"
   Target_ru_ru "Разработано Институтом НИИ Подвала отдела тактикульноведения"
   Modified 1640981216
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D69CEAC1E9BFB9}" {
   Id "DRG-AT_SSO"
   Target_en_us "Scout anti-tank"
   Target_ru_ru "Разведчик-гранатомётчик"
   Modified 1624681510
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{604B22650FBF60AB}" {
   Id "DRG-Automatic_rifleman_assistant"
   Target_en_us "Assistant Automatic Rifleman"
   Target_ru_ru "Помощник пулемётчика"
   Modified 1615539588
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6048E3A3C7FC0B33}" {
   Id "DRG-Automatic_rifleman_RPK"
   Target_en_us "Automatic rifleman"
   Target_ru_ru "Пулемётчик РПК"
   Modified 1615397889
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D6C02F2C2C3EEC}" {
   Id "DRG-Commander_SSO"
   Target_en_us "Spec-Ops Commander"
   Target_ru_ru "Командующий ССО"
   Modified 1640963000
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{604744B0A9F4D6F3}" {
   Id "DRG-COMPANY_LEADER"
   Target_en_us "Company Leader"
   Target_ru_ru "Командир роты"
   Modified 1615283655
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6048E3AB987DEBB7}" {
   Id "DRG-Description_HeaderCDF"
   Target_en_us "Tasks for CDF"
   Target_ru_ru "Задачи для ЧСО"
   Modified 1615401750
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6048E3AB7E2BE2B7}" {
   Id "DRG-Description_HeaderRUS"
   Target_en_us "Tasks for AFRF"
   Target_ru_ru "Задачи для ВС РФ"
   Modified 1615401621
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60477B7A1CFA3768}" {
   Id "DRG-DRIVER"
   Target_en_us "Crew-driver"
   Target_ru_ru "Механик-водитель"
   Modified 1640948359
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60477B7AA35CC11C}" {
   Id "DRG-GUNNER"
   Target_en_us "Crew-Gunner"
   Target_ru_ru "Наводчик-оператор"
   Modified 1640948325
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D6C02FD69A7C32}" {
   Id "DRG-Medic_SSO"
   Target_en_us "Spec-Ops Medic"
   Target_ru_ru "Оператор-медик ССО"
   Modified 1640961762
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D69CE9F9892157}" {
   Id "DRG-MG_SSO"
   Target_en_us "Spec-Ops Machinegunner"
   Target_ru_ru "Пулемётчик ССО"
   Modified 1640959364
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{604744B067136560}" {
   Id "DRG-PLATOON_LEADER"
   Target_en_us "Platoon Leader"
   Target_ru_ru "Командир взвода"
   Modified 1615283535
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D6C02CF3A73204}" {
   Id "DRG-PlatoonLeader_SSO"
   Target_en_us "Squad Platoon Leader"
   Target_ru_ru "Командир развед-взвода"
   Modified 1624689363
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D4A950E1A5DEA1}" {
   Id "DRG-Rifleman_SSO"
   Target_en_us "Spec-Ops Operator"
   Target_ru_ru "Оперативник ССО"
   Modified 1640954027
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED9378F6B6B92}" {
   Id "DRG-Roles_RHS_CrewCommander"
   Target_en_us "Crew-commander"
   Target_ru_ru "Командир экипажа"
   Modified 1640948511
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED93B29CEB228}" {
   Id "DRG-Roles_RHS_Sapper"
   Target_en_us "Sapper Engineer"
   Target_ru_ru "Инженер-сапёр"
   Modified 1640950059
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED93A5CDD5EC9}" {
   Id "DRG-Roles_RHS_SapperLeader"
   Target_en_us "Engineering Group Commander"
   Target_ru_ru "Командир инженерной группы"
   Modified 1640950459
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60477B7FC9D67E7C}" {
   Id "DRG-SNIPER"
   Target_en_us "Sniper"
   Target_ru_ru "Снайпер-истребитель"
   Modified 1615333153
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D4D46322504D8F}" {
   Id "DRG-Sniper_SSO"
   Target_en_us "Spec-Ops Sniper"
   Target_ru_ru "Разведчик-снайпер"
   Modified 1640962086
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60477B7FF537C175}" {
   Id "DRG-SPOTTER"
   Target_en_us "Spotter"
   Target_ru_ru "Снайпер-наблюдатель"
   Modified 1615333120
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D4D46598F5433C}" {
   Id "DRG-Squadleader_SSO"
   Target_en_us "Spec-Ops TeamLeader"
   Target_ru_ru "Командир группы ССО"
   Modified 1640958865
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED174B131E8EA}" {
   Id "DRG-Vest_Ratnik_6B45_MG_Description"
   Target_en_us "Developed in Podval NII"
   Target_ru_ru "Разработано в НИИ Подвала \"Тактиковедении\""
   Modified 1640946292
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED174D502C64A}" {
   Id "DRG-Vest_Ratnik_6B45_MG_Name"
   Target_en_us "Machinegunner vest variant (EMR)"
   Target_ru_ru "Разгрузка пулемётчика в ЕМР"
   Modified 1640946299
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CF39323B5493D8}" {
   Id "DRG_PC_Gen_III_Base_AR_Name"
   Target_en_us "Vest for AR M249"
   Target_ru_ru "Разгрузка пулемётчика M249"
   Modified 1640981106
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEB759F6CAB9E4}" {
   Id "DRG_Roles_RHS_AAT"
   Target_en_us "Assistant anti-tank specialist"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1640942422
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED9311FD65658}" {
   Id "DRG_Roles_RHS_AR_RPK"
   Target_en_us "Automatic rifleman"
   Target_ru_ru "Пулемётчик РПК"
   Modified 1640947086
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEB75B55D06B5E}" {
   Id "DRG_Roles_RHS_AT"
   Target_en_us "Anti-tank specialist"
   Target_ru_ru "Гранатомётчик"
   Modified 1640941314
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEEE215262DF68}" {
   Id "DRG_Roles_RHS_Scout_Leader"
   Target_en_us "Scout Leader"
   Target_ru_ru "Старший разведчик"
   Modified 1640952603
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEEE211B035DE5}" {
   Id "DRG_Roles_RHS_Scout_Sapper"
   Target_en_us "Scout Sapper"
   Target_ru_ru "Разведчик-сапёр"
   Modified 1640952698
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEEE233B6075EA}" {
   Id "DRG_Roles_RHS_ScoutRifleman"
   Target_en_us "Scout"
   Target_ru_ru "Разведчик-стрелок"
   Modified 1640951470
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEEE228F0ABBB2}" {
   Id "DRG_Roles_RHS_ScoutRTO"
   Target_en_us "Scout radio operator"
   Target_ru_ru "Разведчик-радиотелефонист"
   Modified 1640952533
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D69CE45493CFAD}" {
   Id "DRG_Sapper_SSO"
   Target_en_us "Spec-Ops Saboteur"
   Target_ru_ru "Подрывник ССО"
   Modified 1640963691
   Author "hasta"
   LastChanged "hasta"
  }
 }
}