StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60D69CEAC1E9BFB9}" {
   Id "DRG-AT_SSO"
   Target_en_us "Scout anti-tank"
   Target_ru_ru "Разведчик-гранатомётчик"
   Modified 1624681510
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{604B22650FBF60AB}" {
   Id "DRG-Automatic_rifleman_assistant"
   Target_en_us "Assistant Automatic Rifleman"
   Target_ru_ru "Помощник пулемётчика"
   Modified 1615539588
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6048E3A3C7FC0B33}" {
   Id "DRG-Automatic_rifleman_RPK"
   Target_en_us "Automatic rifleman"
   Target_ru_ru "Пулемётчик РПК"
   Modified 1615397889
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D6C02F2C2C3EEC}" {
   Id "DRG-Commander_SSO"
   Target_en_us "Spec-Ops Commander"
   Target_ru_ru "Командующий ССО"
   Modified 1640963000
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{604744B0A9F4D6F3}" {
   Id "DRG-COMPANY_LEADER"
   Target_en_us "Company Leader"
   Target_ru_ru "Командир роты"
   Modified 1615283655
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6048E3AB987DEBB7}" {
   Id "DRG-Description_HeaderCDF"
   Target_en_us "Tasks for CDF"
   Target_ru_ru "Задачи для ЧСО"
   Modified 1615401750
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{628699D4A6720E10}" {
   Id "DRG-Description_HeaderION"
   Target_en_us "Tasks for ION"
   Target_pl_pl "Bóbr, kurwa!"
   Target_ru_ru "Задачи для ИОН"
   Modified 1652990006
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6048E3AB7E2BE2B7}" {
   Id "DRG-Description_HeaderRUS"
   Target_en_us "Tasks for AFRF"
   Target_ru_ru "Задачи для ВС РФ"
   Modified 1615401621
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60477B7A1CFA3768}" {
   Id "DRG-DRIVER"
   Target_en_us "Crew-driver"
   Target_ru_ru "Механик-водитель"
   Modified 1640948359
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60477B7AA35CC11C}" {
   Id "DRG-GUNNER"
   Target_en_us "Crew-Gunner"
   Target_ru_ru "Наводчик-оператор"
   Modified 1640948325
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D6C02FD69A7C32}" {
   Id "DRG-Medic_SSO"
   Target_en_us "Spec-Ops Medic"
   Target_ru_ru "Оператор-медик ССО"
   Modified 1640961762
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D69CE9F9892157}" {
   Id "DRG-MG_SSO"
   Target_en_us "Spec-Ops Machinegunner"
   Target_ru_ru "Пулемётчик ССО"
   Modified 1640959364
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{604744B067136560}" {
   Id "DRG-PLATOON_LEADER"
   Target_en_us "Platoon Leader"
   Target_ru_ru "Командир взвода"
   Modified 1615283535
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D6C02CF3A73204}" {
   Id "DRG-PlatoonLeader_SSO"
   Target_en_us "Squad Platoon Leader"
   Target_ru_ru "Командир развед-взвода"
   Modified 1624689363
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D4A950E1A5DEA1}" {
   Id "DRG-Rifleman_SSO"
   Target_en_us "Spec-Ops Operator"
   Target_ru_ru "Оперативник ССО"
   Modified 1683291846
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6454F7D05B5A39E5}" {
   Id "DRG-Rifleman_SSO_RER"
   Target_en_us "Spec-Ops Operator"
   Target_ru_ru "Оперативник ССО РЭР"
   Modified 1683321908
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED9378F6B6B92}" {
   Id "DRG-Roles_RHS_CrewCommander"
   Target_en_us "Crew-commander"
   Target_ru_ru "Командир экипажа"
   Modified 1640948511
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED93B29CEB228}" {
   Id "DRG-Roles_RHS_Sapper"
   Target_en_us "Sapper Engineer"
   Target_ru_ru "Инженер-сапёр"
   Modified 1640950059
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED93A5CDD5EC9}" {
   Id "DRG-Roles_RHS_SapperLeader"
   Target_en_us "Engineering Group Commander"
   Target_ru_ru "Командир инженерной группы"
   Modified 1640950459
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6454F7818C721A31}" {
   Id "DRG-Scam-Dollars"
   Target_en_us "Scam dollars"
   Modified 1683298315
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6454F7955932DBED}" {
   Id "DRG-SMAW_AT_SSO"
   Target_en_us "Spec-Ops Operator SMAW"
   Target_ru_ru "Оператор-ПТ SMAW ССО"
   Modified 1683292341
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60477B7FC9D67E7C}" {
   Id "DRG-SNIPER"
   Target_en_us "Sniper"
   Target_ru_ru "Снайпер-истребитель"
   Modified 1615333153
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D4D46322504D8F}" {
   Id "DRG-Sniper_SSO"
   Target_en_us "Spec-Ops Sniper"
   Target_ru_ru "Снайпер ССО"
   Modified 1641068534
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60477B7FF537C175}" {
   Id "DRG-SPOTTER"
   Target_en_us "Spotter"
   Target_ru_ru "Снайпер-наблюдатель"
   Modified 1615333120
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D4D46598F5433C}" {
   Id "DRG-Squadleader_SSO"
   Target_en_us "Spec-Ops TeamLeader"
   Target_ru_ru "Командир группы ССО"
   Modified 1640958865
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6454F7904A5EBA4E}" {
   Id "DRG-Squadleader_SSO_Officer"
   Target_en_us "Spec-Ops Officer"
   Target_ru_ru "Офицер ССО"
   Modified 1683290596
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6454F7928D5A7D86}" {
   Id "DRG-SR_SSO"
   Target_en_us "Spec-Ops Senior Operator"
   Target_ru_ru "Старший оперативник ССО"
   Modified 1683291826
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED174B131E8EA}" {
   Id "DRG-Vest_Ratnik_6B45_MG_Description"
   Target_en_us "Developed in Podval NII"
   Target_ru_ru "Разработано в НИИ Подвала \"Тактиковедении\""
   Modified 1640946292
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED174D502C64A}" {
   Id "DRG-Vest_Ratnik_6B45_MG_Name"
   Target_en_us "Machinegunner vest variant (EMR)"
   Target_ru_ru "Разгрузка пулемётчика в ЕМР"
   Modified 1640946299
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6222CD29E41B405D}" {
   Id "DRG_ChangeFlagAction"
   Target_en_us "Change flag"
   Target_ru_ru "Поменять флаг"
   Modified 1646448211
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{628699D7D2786DB1}" {
   Id "DRG_ION_PlatoonLeader"
   Target_en_us "Platoon Leader ION"
   Target_ru_ru "Главарь боевиков ION"
   Modified 1652989173
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{628699D0ECB4522C}" {
   Id "DRG_ION_RadioEng"
   Target_en_us "Radio-Specialist ION"
   Target_ru_ru "Специалист РЭР ИОН"
   Modified 1652991681
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{628683598FD08E86}" {
   Id "DRG_ION_Rifleman"
   Target_en_us "ION Figther"
   Target_ru_ru "Боевик ИОН"
   Modified 1652987440
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6286835A8AB49ECC}" {
   Id "DRG_ION_Sapper"
   Target_en_us "Sapper ION"
   Target_ru_ru "Сапёр ИОН"
   Modified 1652987909
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6286835B30D45AFD}" {
   Id "DRG_ION_TeamLeader"
   Target_en_us "TeamLeader ION"
   Target_ru_ru "Командир группы ИОН"
   Modified 1652988057
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CF39320BCCAA57}" {
   Id "DRG_PC_Gen_III_Base_AR_Desc"
   Target_en_us "Developed by Podval"
   Target_ru_ru "Разработано Институтом НИИ Подвала отдела тактикульноведения"
   Modified 1641075505
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CF39323B5493D8}" {
   Id "DRG_PC_Gen_III_Base_AR_Name"
   Target_en_us "Vest for AR M249"
   Target_ru_ru "Разгрузка пулемётчика M249"
   Modified 1640981106
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6454F7AD451DAEA0}" {
   Id "DRG_Policeman"
   Target_en_us "Policeman"
   Target_ru_ru "Полицейский"
   Modified 1683319391
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271FB644B10C1}" {
   Id "DRG_RifleSquad"
   Target_en_us "Rifle squad"
   Target_ru_ru "Стрелковое отделение"
   Modified 1690464825
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{633283561F8E584A}" {
   Id "DRG_Role_AT_TeamLeader"
   Target_en_us "TeamLeader AT Squad"
   Target_ru_ru "Командир ПТ расчёта"
   Modified 1664256388
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{63328351A098CC85}" {
   Id "DRG_Role_AT_Unit"
   Target_en_us "AT Assistant"
   Target_ru_ru "Номер ПТ расчёта"
   Modified 1664257083
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C6912F0801D58C}" {
   Id "DRG_Role_MTO_Engineer"
   Target_en_us "Logistics Engineer"
   Target_ru_ru "Инженер МТО"
   Modified 1690740006
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C6912F86701E56}" {
   Id "DRG_Role_MTO_EngineerSenior"
   Target_en_us "Senior Logistics Engineer"
   Target_ru_ru "Старший инженер МТО"
   Modified 1690740194
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEB759F6CAB9E4}" {
   Id "DRG_Roles_RHS_AAT"
   Target_en_us "Assistant anti-tank specialist"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1640942422
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CED9311FD65658}" {
   Id "DRG_Roles_RHS_AR_RPK"
   Target_en_us "Automatic rifleman"
   Target_ru_ru "Пулемётчик РПК"
   Modified 1640947086
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEB75B55D06B5E}" {
   Id "DRG_Roles_RHS_AT"
   Target_en_us "Anti-tank specialist"
   Target_ru_ru "Гранатомётчик"
   Modified 1640941314
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEEE215262DF68}" {
   Id "DRG_Roles_RHS_Scout_Leader"
   Target_en_us "Scout Leader"
   Target_ru_ru "Старший разведчик"
   Modified 1640952603
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271FD095BBB88}" {
   Id "DRG_Roles_RHS_Scout_REW"
   Target_en_us "Electronic intelligence specialist"
   Target_ru_ru "Специалист РЭР"
   Modified 1690467747
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEEE211B035DE5}" {
   Id "DRG_Roles_RHS_Scout_Sapper"
   Target_en_us "Scout Sapper"
   Target_ru_ru "Разведчик-сапёр"
   Modified 1640952698
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEEE233B6075EA}" {
   Id "DRG_Roles_RHS_ScoutRifleman"
   Target_en_us "Scout"
   Target_ru_ru "Разведчик-стрелок"
   Modified 1640951470
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CEEE228F0ABBB2}" {
   Id "DRG_Roles_RHS_ScoutRTO"
   Target_en_us "Scout radio operator"
   Target_ru_ru "Разведчик-радиотелефонист"
   Modified 1640952533
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{60D69CE45493CFAD}" {
   Id "DRG_Sapper_SSO"
   Target_en_us "Spec-Ops Saboteur"
   Target_ru_ru "Подрывник ССО"
   Modified 1640963691
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6454F7AD163C0F5C}" {
   Id "DRG_Senior_Policeman"
   Target_ru_ru "Старший полицейский"
   Modified 1683319477
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271F92501C381}" {
   Id "DRG_Sqd_AT"
   Target_en_us "Anti-tank team"
   Target_ru_ru "Противотанковый расчёт"
   Modified 1690465927
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271FBAF39752F}" {
   Id "DRG_Sqd_Engineer"
   Target_en_us "Engineer and sapper section."
   Target_ru_ru "Инженерно-сапёрная группа"
   Modified 1690465158
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C69122FA312D9A}" {
   Id "DRG_Sqd_HeliRocket"
   Target_en_us "Attack helicopter crew"
   Target_ru_ru "Экипаж ударного вертолёта"
   Modified 1690738368
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271FBFFF3E8F4}" {
   Id "DRG_Sqd_Hq"
   Target_en_us "Headquarter"
   Target_ru_ru "Командование"
   Modified 1690465039
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271F937C5724C}" {
   Id "DRG_Sqd_Mg"
   Target_en_us "Machine gunner squad"
   Target_ru_ru "Пулемётное отделение"
   Modified 1690465825
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C6912CF239D021}" {
   Id "DRG_Sqd_MTO"
   Target_en_us "Material and technical support"
   Target_ru_ru "Материально техническое обеспечение"
   Modified 1690739529
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271FA8EC6260B}" {
   Id "DRG_Sqd_PlHq"
   Target_en_us "Platoon HQ"
   Target_ru_ru "Управление взвода"
   Modified 1690465672
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271FB2F525D5F}" {
   Id "DRG_Sqd_Rifle"
   Target_en_us "Rifle squad"
   Target_ru_ru "Стрелковое отделение"
   Modified 1690464941
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271F9DD50E11E}" {
   Id "DRG_Sqd_Snip"
   Target_en_us "Sniper team"
   Target_ru_ru "Снайперский расчёт"
   Modified 1690465975
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64C271FB955327D2}" {
   Id "DRG_Sqd_SSO"
   Target_en_us "Sabotage group"
   Target_ru_ru "Диверсионная группа"
   Modified 1690465242
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62868352D24FB61B}" {
   Id "DRG_SS_rifleman"
   Target_en_us "Security service officer"
   Target_ru_ru "Оперативник службы безопасности"
   Modified 1652983936
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61D2C04C20454E0C}" {
   Id "DRG_TKR_Roles_AT"
   Target_en_us "Rebel AT"
   Target_ru_ru "Боевик гранатомётчик"
   Modified 1641211158
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61D2C04B3C2294F6}" {
   Id "DRG_TKR_Roles_CL"
   Target_en_us "Rebel Leader"
   Target_ru_ru "Главарь боевиков"
   Modified 1641211566
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61D2C04D0433B923}" {
   Id "DRG_TKR_Roles_MachineGunner"
   Target_en_us "Rebel Machinegunner"
   Target_ru_ru "Боевик пулемётчик"
   Modified 1641210761
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61D2C04C88E60C22}" {
   Id "DRG_TKR_Roles_PL"
   Target_en_us "Rebel Platoon Leader"
   Target_ru_ru "Командир боевой ячейки"
   Modified 1641211440
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61D2C0510CDBBC88}" {
   Id "DRG_TKR_Roles_Rifleman"
   Target_en_us "Rebel"
   Target_ru_ru "Боевик"
   Modified 1641208761
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61D2EE9512C4CDEE}" {
   Id "DRG_TKR_Roles_Sapper"
   Target_en_us "Rebel sapper"
   Target_ru_ru "Боевик подрывник"
   Modified 1641215887
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61D2C0506FA5D411}" {
   Id "DRG_TKR_Roles_SL"
   Target_en_us "Rebel Squad Leader"
   Target_ru_ru "Командир отряда боевиков"
   Modified 1641208982
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61D2C051A78E14B7}" {
   Id "DRG_TKR_Roles_TL"
   Target_en_us "Rebel Team Leader"
   Target_ru_ru "Опытный боевик"
   Modified 1641208874
   Author "hasta"
   LastChanged "hasta"
  }
 }
}