StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{604744B0A9F4D6F3}" {
   Id "DRG-COMPANY_LEADER"
   Target_en_us "Company Leader"
   Target_ru_ru "Командир роты"
   Modified 1615283655
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{604744B067136560}" {
   Id "DRG-PLATOON_LEADER"
   Target_en_us "Platoon Leader"
   Target_ru_ru "Командир взвода"
   Modified 1615283535
   Author "hasta"
   LastChanged "hasta"
  }
 }
}