StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{63254DFBEB1CA1DE}" {
   Id "DRG_2B14_backpack"
   Target_en_us "2B14  mortar gun in a backpack."
   Target_ru_ru "Орудие миномёта 2Б14 в рюкзаке"
   Modified 1663389852
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{63254DFBB93A95D4}" {
   Id "DRG_2B14_bipod_backpack"
   Target_en_us "2B14 bipod and plate"
   Target_ru_ru "Двунога и плита 2Б14"
   Modified 1663389895
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{63253172DC50721E}" {
   Id "DRG_assemble_mortar"
   Target_en_us "Assamble mortar"
   Target_ru_ru "Собрать миномёт"
   Modified 1663386140
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{632531728D45C213}" {
   Id "DRG_disassemble_weapon"
   Target_en_us "Disassemble mortar"
   Target_ru_ru "Разобрать миномёт"
   Modified 1663389941
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{63254DFB4193AE34}" {
   Id "DRG_m252_backpack"
   Target_en_us "M252 mortar gun in a backpack."
   Target_ru_ru "Орудие миномёта M252 в рюкзаке"
   Modified 1663389333
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{63254DFB10069A42}" {
   Id "DRG_m252_bipod_backpack"
   Target_en_us "M252 bipod and plate"
   Target_ru_ru "Двунога и плита M252"
   Modified 1663389411
   Author "hasta"
   LastChanged "hasta"
  }
 }
}