StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{63253172DC50721E}" {
   Id "DRG_assemble_mortar"
   Target_en_us "Assamble mortar"
   Target_ru_ru "Собрать миномёт"
   Modified 1663386140
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{632531728D45C213}" {
   Id "DRG_disassemble_weapon"
   Target_en_us "Disassemble Weapon"
   Target_ru_ru "Разобрать оружие"
   Modified 1663386253
   Author "hasta"
   LastChanged "hasta"
  }
 }
}