StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6058B3C66654C4FD}" {
   Id "DRG-Faction_PMC_EC"
   Target_en_us "PMC «EC»"
   Target_ru_ru "ЧВК  «ЭК»"
   Modified 1616443395
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6059361D330C80AD}" {
   Id "DRG-Role_AAT"
   Target_en_us "Assistant AT Gunner"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1616460736
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6059361F369C759A}" {
   Id "DRG-Role_AT"
   Target_en_us "AT Gunner"
   Target_ru_ru "Гранатомётчик"
   Modified 1616459843
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{605903B4CDF26F1C}" {
   Id "DRG-Role_SquadLeader"
   Target_en_us "Squad Leader"
   Target_ru_ru "Командир отряда"
   Modified 1616448742
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6058F54153764737}" {
   Id "DRG-Role_Stormtrooper"
   Target_en_us "Stormtrooper"
   Target_ru_ru "Штурмовик"
   Modified 1616444288
   Author "hasta"
   LastChanged "hasta"
  }
 }
}