StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6058B3C66654C4FD}" {
   Id "DRG-Faction_PMC_EC"
   Target_en_us "PMC «EC»"
   Target_ru_ru "ЧВК  «ЭК»"
   Modified 1616443395
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6059361D330C80AD}" {
   Id "DRG-Role_AAT"
   Target_en_us "Assistant AT Gunner"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1616460736
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6059361F369C759A}" {
   Id "DRG-Role_AT"
   Target_en_us "AT Gunner"
   Target_ru_ru "Гранатомётчик"
   Modified 1616459843
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{605B46D35D763797}" {
   Id "DRG-Role_CL"
   Target_en_us "Company Leader"
   Target_ru_ru "Командир роты"
   Modified 1616599261
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{605B46DE0B44EA75}" {
   Id "DRG-Role_MG"
   Target_en_us "Machine gunner"
   Target_ru_ru "Пулемётчик-штурмовик"
   Modified 1616596588
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{605B46D2F8913FB7}" {
   Id "DRG-Role_PL"
   Target_en_us "Group Leader"
   Target_ru_ru "Командир группы"
   Modified 1616598997
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{605B46DC124C61DB}" {
   Id "DRG-Role_Sniper"
   Target_en_us "Marksman"
   Target_ru_ru "Снайпер"
   Modified 1616597763
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{605903B4CDF26F1C}" {
   Id "DRG-Role_SquadLeader"
   Target_en_us "Squad Leader"
   Target_ru_ru "Командир штурмового отряда"
   Modified 1616598835
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6058F54153764737}" {
   Id "DRG-Role_Stormtrooper"
   Target_en_us "Stormtrooper"
   Target_ru_ru "Штурмовик"
   Modified 1616444288
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{605B46DE7D911F6A}" {
   Id "DRG-Role_TL"
   Target_en_us "Team Leader"
   Target_ru_ru "Командир штурмового звена"
   Modified 1616597121
   Author "hasta"
   LastChanged "hasta"
  }
 }
}