StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6054C4B807B273E9}" {
   Id "DRG-Callsign_GTF_Company_A"
   Target_en_us "Anabah"
   Target_ru_ru "Анаба"
   Modified 1616170387
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B80D4D05E7}" {
   Id "DRG-Callsign_GTF_Company_B"
   Target_en_us "Barqah"
   Target_ru_ru "Барка"
   Modified 1616170402
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B80F4B7FB8}" {
   Id "DRG-Callsign_GTF_Company_C"
   Target_en_us "Carima "
   Target_ru_ru "Карима"
   Modified 1616170551
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B809362F98}" {
   Id "DRG-Callsign_GTF_Company_D"
   Target_en_us "Dara"
   Target_ru_ru "Дара"
   Modified 1616170568
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B80AA6EAD4}" {
   Id "DRG-Callsign_GTF_Company_E"
   Modified 1616169581
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B814DBDF39}" {
   Id "DRG-Callsign_GTF_Company_F"
   Target_en_us "Filaq"
   Target_ru_ru "Филак"
   Modified 1616170660
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B81636A4B7}" {
   Id "DRG-Callsign_GTF_Company_G"
   Target_en_us "Ghadab"
   Target_ru_ru "Гадаб"
   Modified 1616170672
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B8179F1069}" {
   Id "DRG-Callsign_GTF_Company_H"
   Modified 1616169590
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B81834626C}" {
   Id "DRG-Callsign_GTF_Platoon_1"
   Modified 1616169608
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B81993D789}" {
   Id "DRG-Callsign_GTF_Platoon_2"
   Modified 1616169610
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B81BD7B7BD}" {
   Id "DRG-Callsign_GTF_Platoon_3"
   Modified 1616169613
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B861D4DB61}" {
   Id "DRG-Callsign_GTF_Platoon_4"
   Modified 1616170063
   Author "hasta"
   LastChanged "hasta"
  }
 }
}