StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6054C4B807B273E9}" {
   Id "DRG-Callsign_GTF_Company_A"
   Target_en_us "Anabah"
   Target_ru_ru "Анаба"
   Modified 1616170387
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B80D4D05E7}" {
   Id "DRG-Callsign_GTF_Company_B"
   Target_en_us "Barqah"
   Target_ru_ru "Барка"
   Modified 1616170402
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B80F4B7FB8}" {
   Id "DRG-Callsign_GTF_Company_C"
   Target_en_us "Carima "
   Target_ru_ru "Карима"
   Modified 1616170551
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B809362F98}" {
   Id "DRG-Callsign_GTF_Company_D"
   Target_en_us "Dara"
   Target_ru_ru "Дара"
   Modified 1616170568
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B80AA6EAD4}" {
   Id "DRG-Callsign_GTF_Company_E"
   Target_en_us "Esharat"
   Target_ru_ru "Эшарат"
   Modified 1616171308
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B814DBDF39}" {
   Id "DRG-Callsign_GTF_Company_F"
   Target_en_us "Filaq"
   Target_ru_ru "Филак"
   Modified 1616170660
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B81636A4B7}" {
   Id "DRG-Callsign_GTF_Company_G"
   Target_en_us "Ghadab"
   Target_ru_ru "Гадаб"
   Modified 1616170672
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B8179F1069}" {
   Id "DRG-Callsign_GTF_Company_H"
   Target_en_us "Hujum"
   Target_ru_ru "Худжум"
   Modified 1616170720
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B81834626C}" {
   Id "DRG-Callsign_GTF_Platoon_1"
   Target_en_us "Alif"
   Target_ru_ru "Алиф"
   Modified 1616171491
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B81993D789}" {
   Id "DRG-Callsign_GTF_Platoon_2"
   Target_en_us "Bahr"
   Target_ru_ru "Бахр"
   Modified 1616171506
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B81BD7B7BD}" {
   Id "DRG-Callsign_GTF_Platoon_3"
   Target_en_us "Cairo"
   Target_ru_ru "Каиро"
   Modified 1616171526
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6054C4B861D4DB61}" {
   Id "DRG-Callsign_GTF_Platoon_4"
   Target_en_us "Dune"
   Target_ru_ru "Дюн"
   Modified 1616171543
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{605504E117BA1FFF}" {
   Id "DRG-Role_CompanyLeader"
   Target_en_us "Field commander"
   Target_ru_ru "Полевой командир"
   Modified 1616197786
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{605504E10BB16D78}" {
   Id "DRG-Role_PlatoonLeader"
   Target_en_us "Group commander"
   Target_ru_ru "Командир группы"
   Modified 1616197761
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{605504E10EB3A66A}" {
   Id "DRG-Role_SquadLeader"
   Target_en_us "Squad Commander"
   Target_ru_ru "Командир отряда"
   Modified 1616197732
   Author "hasta"
   LastChanged "hasta"
  }
 }
}