StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{61B543EF74F189EC}" {
   Id "DRG-Role_AntiTank"
   Target_en_us "Anti-Tank Specialist"
   Target_ru_ru "Гранатомётчик"
   Modified 1639283730
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D20F4503DA}" {
   Id "DRG-Role_AntiTankAssistant"
   Target_en_us "Anti-Tank Assistant"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1639317917
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D639D70EE4}" {
   Id "DRG-Role_CrewDriver"
   Target_en_us "Crew Driver"
   Target_ru_ru "Механик-водитель"
   Modified 1639319711
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D66CC845E4}" {
   Id "DRG-Role_CrewGunner"
   Target_en_us "Crew Gunner"
   Target_ru_ru "Наводчик-оператор"
   Modified 1639319788
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D551D4FF581}" {
   Id "DRG-Role_EngineerSapper"
   Target_en_us "Engineer Sapper"
   Target_ru_ru "Инженер сапёр"
   Modified 1639346789
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D7D6CFDE6C}" {
   Id "DRG-Role_Recon"
   Target_en_us "Scout"
   Target_ru_ru "Разведчик"
   Modified 1639352849
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D47D30DA77D}" {
   Id "DRG-Role_Recon_Medic"
   Target_en_us "Scout Medic"
   Target_ru_ru "Разведчик-санитар"
   Modified 1639353787
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B8A51EA1FA9D35}" {
   Id "DRG-Role_Recon_Officer"
   Target_en_us "Scount Officer"
   Target_ru_ru "Офицер разведки"
   Modified 1639495009
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D59F2619D28}" {
   Id "DRG-Role_Recon_PL"
   Target_en_us "Scout Platoon Leader"
   Target_ru_ru "Командир развед.взвода"
   Modified 1639352821
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D5ADE31F74D}" {
   Id "DRG-Role_ReconAR"
   Target_en_us "Scout Automatic Rifleman"
   Target_ru_ru "Разведчик-пулемётчик"
   Modified 1639352433
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D596818E85B}" {
   Id "DRG-Role_ReconAT"
   Target_en_us "Scount Aniti-Tank Specialist"
   Target_ru_ru "Разведчик-гранатомётчик"
   Modified 1639352577
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B8A5135CBA7D37}" {
   Id "DRG-Role_ReconBearer"
   Target_en_us "Scout Ammo Bearer"
   Target_ru_ru "Разведчик-подносчик"
   Modified 1639493995
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D44D597D0A}" {
   Id "DRG-Role_ReconRifleman"
   Target_en_us "Scount Rifleman"
   Target_ru_ru "Разведчик-стрелок"
   Modified 1639347238
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D5A52FF55AA}" {
   Id "DRG-Role_ReconRTO"
   Target_en_us "Scout RTO"
   Target_ru_ru "Разведчик-радиотелефонист"
   Modified 1639352186
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D54696A9850}" {
   Id "DRG-Role_ReconSapper"
   Target_en_us "Scount Sapper"
   Target_ru_ru "Разведчик-сапёр"
   Modified 1639347280
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B613230BF7A35A}" {
   Id "DRG-Role_ReconSeniorScount"
   Target_en_us "Senior Scount"
   Target_ru_ru "Старший разведчик"
   Modified 1639322535
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D5B5682B098}" {
   Id "DRG-Role_ReconSL"
   Target_en_us "Scout Leader"
   Target_ru_ru "Командир развед.группы"
   Modified 1639351733
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D54C3A5D447}" {
   Id "DRG-Role_ReconSniper"
   Target_en_us "Scount Sniper"
   Target_ru_ru "Разведчик-снайпер"
   Modified 1639347871
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6170D2157DE458A0}" {
   Id "DRG-Role_Watchman"
   Target_en_us "Old watchman"
   Target_ru_ru "Старый сторож"
   Modified 1639283579
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CB0A080F880E4D}" {
   Id "DRG-Weapon_NSP_Description"
   Target_en_us "Ground signal cartridge NSP, orange smoke. Used by the Soviet Army to send signals. Most often to indicate their positions in the event of friendly fire."
   Target_ru_ru "Наземный сигнальный патрон НСП, оранжевый дым. Используется Советсткой Армии для подачи сигналов. Чаще всего для обозначения своих позиций в случае дружественного огня."
   Modified 1640696647
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CB0A082F65E9E8}" {
   Id "DRG-Weapon_NSP_Name"
   Target_en_us "NSP"
   Target_ru_ru "НСП"
   Modified 1640696536
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62BED26AD2D8D92B}" {
   Id "DRG_ChangeFlagAction"
   Target_en_us "Change flag"
   Target_ru_ru "Поменять флаг"
   Modified 1656675458
   Author "hasta"
   LastChanged "hasta"
  }
 }
}