StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6170D2157DE458A0}" {
   Id "#DRG-Role_Watchman"
   Target_en_us "Old watchman"
   Target_ru_ru "Старый сторож"
   Modified 1634784421
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6170D2176D808F8E}" {
   Id "DRG-Role_Watchman"
   Target_en_us "Old watchman"
   Target_ru_ru "Старый сторож"
   Modified 1634785297
   Author "hasta"
   LastChanged "hasta"
  }
 }
}