StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{61B543EF74F189EC}" {
   Id "DRG-Role_AntiTank"
   Target_en_us "Anti-Tank Specialist"
   Target_ru_ru "Гранатомётчик"
   Modified 1639283730
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D20F4503DA}" {
   Id "DRG-Role_AntiTankAssistant"
   Target_en_us "Anti-Tank Assistant"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1639317917
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D639D70EE4}" {
   Id "DRG-Role_CrewDriver"
   Target_en_us "Crew Driver"
   Target_ru_ru "Механик-водитель"
   Modified 1639319711
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D66CC845E4}" {
   Id "DRG-Role_CrewGunner"
   Target_en_us "Crew Gunner"
   Target_ru_ru "Наводчик-оператор"
   Modified 1639319788
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D7D6CFDE6C}" {
   Id "DRG-Role_Recon"
   Target_en_us "Recon"
   Target_ru_ru "Разведчик"
   Modified 1639320576
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D44D597D0A}" {
   Id "DRG-Role_ReconRifleman"
   Target_en_us "Recon Rifleman"
   Target_ru_ru "Разведчик-стрелок"
   Modified 1639320769
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B613230BF7A35A}" {
   Id "DRG-Role_ReconSeniorScount"
   Target_en_us "Senior Scount"
   Target_ru_ru "Старший разведчик"
   Modified 1639322535
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6170D2157DE458A0}" {
   Id "DRG-Role_Watchman"
   Target_en_us "Old watchman"
   Target_ru_ru "Старый сторож"
   Modified 1639283579
   Author "hasta"
   LastChanged "hasta"
  }
 }
}